# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=21.6.2
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="NestJS/Prisma"

# NestJS/Prisma app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="development"


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp openssl pkg-config python-is-python3

# Install node modules
COPY --link package-lock.json package.json ./
RUN npm ci --include=dev

# Generate Prisma Client
COPY --link prisma .
RUN npx prisma generate

# Copy application code
COPY --link . .

# Dummy URL to allow the build to complete
ENV DATABASE_URL='postgresql://user:password@host:5432/ts-db'
# Build application
RUN npm run build

# Final stage for app image
FROM base

# Install packages needed for deployment and debugging
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    openssl \
    redis-tools \
    postgresql-client \
    curl \
    vim \
    htop \
    net-tools \
    telnet \
    dnsutils \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Copy built application
COPY --from=build /app /app

# Copy the entrypoint script from the docker folder into /app
COPY --link docker/entrypoint.sh ./entrypoint.sh

# Ensure the entrypoint has execute permission
RUN chmod +x ./entrypoint.sh

# Start the server by default, this can be overwritten at runtime
EXPOSE 3001
ENTRYPOINT ./entrypoint.sh
