services:
  thinkstorm-backend-dev:
    image: thinkstorm-backend-dev:latest
    environment:
      TYPE: development
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_UNIT_TEST_URL: ${DATABASE_UNIT_TEST_URL}
      DATABASE_E2E_TEST_URL: ${DATABASE_E2E_TEST_URL}
      DATABASE_COVERAGE_TEST_URL: ${DATABASE_COVERAGE_TEST_URL}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_CACHING_TTL: ${REDIS_CACHING_TTL}
      REDIS_THROTTLER_URL: ${REDIS_THROTTLER_URL}
      REDIS_CACHING_URL: ${REDIS_CACHING_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_FROM: ${MAIL_FROM}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_STORAGE_BUCKET: ${SUPABASE_STORAGE_BUCKET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '${HOST_PORT:-3001}:3001'
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy
    networks:
      - backend-network
