services:
  thinkstorm-backend-dev:
    image: thinkstorm-backend-dev:latest
    environment:
      TYPE: development
      DATABASE_URL: 'postgresql://postgres:postgres@thinkstorm-postgres-db:5432/postgres'
      REDIS_CACHING_TTL: ${REDIS_CACHING_TTL}
      REDIS_THROTTLER_URL: ${REDIS_THROTTLER_URL}
      REDIS_CACHING_URL: ${REDIS_CACHING_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
      ENVELOOP_API_KEY: ${ENVELOOP_API_KEY}
    ports:
      - '${HOST_PORT:-3001}:3001'
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy
    networks:
      - backend-network
