export const domainLabel = [
  { name: 'Web Development' },
  { name: 'Mobile Development' },
  { name: 'Desktop Development' },
  { name: 'Game Development' },
  { name: 'Data Science' },
  { name: 'Machine Learning' },
  { name: 'Artificial Intelligence' },
  { name: 'Cybersecurity' },
  { name: 'DevOps' },
  { name: 'Cloud Computing' },
  { name: 'Database Management' },
  { name: 'Software Testing' },
  { name: 'UI/UX Design' },
  { name: 'Product Management' },
  { name: 'Project Management' },
  { name: 'Business Analysis' },
  { name: 'Marketing' },
  { name: 'Sales' },
  { name: 'Customer Support' },
  { name: 'Human Resources' },
  { name: 'Finance' },
  { name: 'Legal' },
  { name: 'Healthcare' },
  { name: 'Education' },
  { name: 'Entertainment' },
  { name: 'Travel' },
  { name: 'Food & Beverage' },
  { name: 'Fashion' },
  { name: 'Sports' },
  { name: 'Automotive' },
  { name: 'Real Estate' },
  { name: 'E-commerce' },
  { name: 'Social Media' },
  { name: 'Gaming' },
  { name: 'Music' },
  { name: 'Video' },
  { name: 'Audio' },
  { name: 'Photography' },
  { name: 'Art' },
  { name: 'Writing' },
  { name: 'Reading' },
  { name: 'Learning' },
  { name: 'Teaching' },
  { name: 'Mentoring' },
  { name: 'Coaching' },
  { name: 'Consulting' },
  { name: 'Freelancing' },
  { name: 'Entrepreneurship' },
  { name: 'Investing' },
  { name: 'Trading' },
  { name: 'Gardening' },
  { name: 'Cooking' },
  { name: 'Baking' },
  { name: 'Mixology' },
  { name: 'Fitness' },
  { name: 'Yoga' },
  { name: 'Meditation' },
  { name: 'Mindfulness' },
  { name: 'Spirituality' },
  { name: 'Religion' },
  { name: 'Philosophy' },
  { name: 'Psychology' },
  { name: 'Sociology' },
  { name: 'Anthropology' },
  { name: 'History' },
  { name: 'Geography' },
  { name: 'Economics' },
  { name: 'Politics' },
  { name: 'Law' },
  { name: 'Science' },
  { name: 'Technology' },
  { name: 'Engineering' },
  { name: 'Mathematics' },
  { name: 'Physics' },
  { name: 'Chemistry' },
  { name: 'Biology' },
  { name: 'Medicine' },
  { name: 'Nursing' },
  { name: 'Dentistry' },
  { name: 'Pharmacy' },
  { name: 'Veterinary' },
  { name: 'Agriculture' },
  { name: 'Forestry' },
  { name: 'Fishery' },
  { name: 'Mining' },
  { name: 'Manufacturing' },
  { name: 'Construction' },
  { name: 'Transportation' },
  { name: 'Logistics' },
  { name: 'Warehousing' },
  { name: 'Retail' },
  { name: 'Hospitality' },
  { name: 'Tourism' },
  { name: 'Real Estate' },
  { name: 'Banking' },
  { name: 'Insurance' },
  { name: 'Investment' },
  { name: 'Accounting' },
  { name: 'Taxation' },
  { name: 'Audit' },
  { name: 'Consulting' },
  { name: 'Legal' },
  { name: 'Compliance' },
  { name: 'Regulation' },
  { name: 'Policy' },
  { name: 'Public Administration' },
  { name: 'Nonprofit' },
  { name: 'Social Work' },
  { name: 'Public Health' },
  { name: 'Education' },
  { name: 'Research' },
  { name: 'Development' },
  { name: 'Design' }
];