import { Goal, ProjectStatus, LanguageCode } from '@prisma/client';

export const mockProjects = [
  {
    title: 'Eco-Friendly Shopping App',
    description:
      'An app that helps users find and support local eco-friendly businesses',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-12-31'),
    domainLabels: ['E-commerce', 'Technology'],
    technicalLabels: ['React', 'Express', 'PostgreSQL'],
  },
  {
    title: 'Language Learning Platform',
    description:
      'Interactive platform for learning new languages through gamification',
    goal: Goal.Education,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-10-15'),
    domainLabels: ['Education', 'Teaching'],
    technicalLabels: ['TypeScript', 'MongoDB', 'Express'],
  },
  {
    title: 'Fitness Tracker',
    description:
      'Comprehensive fitness tracking app with AI-powered workout suggestions',
    goal: Goal.Profitable,
    status: ProjectStatus.Complete,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-06-30'),
    domainLabels: ['Fitness', 'Healthcare'],
    technicalLabels: ['React', 'iOS', 'MongoDB'],
  },
  {
    title: 'Open Source CMS',
    description: 'A modern content management system built for developers',
    goal: Goal.OpenSource,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-09-01'),
    domainLabels: ['Web Development', 'Technology'],
    technicalLabels: ['PHP', 'MySQL', 'Vue.js'],
  },
  {
    title: 'Recipe Sharing Community',
    description: 'Platform for sharing and discovering new recipes',
    goal: Goal.Fun,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.FR,
    milestone: new Date('2024-08-15'),
    domainLabels: ['Food & Beverage', 'Social Media'],
    technicalLabels: ['Django', 'PostgreSQL', 'React'],
  },
  {
    title: 'Smart Home Automation',
    description: 'Open source home automation system',
    goal: Goal.OpenSource,
    status: ProjectStatus.OnHold,
    languageCode: LanguageCode.DE,
    milestone: new Date('2024-11-30'),
    domainLabels: ['Technology', 'Engineering'],
    technicalLabels: ['Python', 'Raspberry Pi', 'MongoDB'],
  },
  {
    title: 'Virtual Art Gallery',
    description: '3D virtual gallery for artists to showcase their work',
    goal: Goal.Fun,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-07-20'),
    domainLabels: ['Art', 'Web Development'],
    technicalLabels: ['JavaScript', 'React', 'Express'],
  },
  {
    title: 'Sustainable Travel Guide',
    description: 'App for finding eco-friendly travel options',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.ES,
    milestone: new Date('2024-10-01'),
    domainLabels: ['Travel', 'Tourism'],
    technicalLabels: ['Android', 'iOS', 'MongoDB'],
  },
  {
    title: 'Mental Health Journal',
    description: 'Private journaling app with mood tracking',
    goal: Goal.Education,
    status: ProjectStatus.Complete,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-05-15'),
    domainLabels: ['Healthcare', 'Psychology'],
    technicalLabels: ['Swift', 'iOS', 'SQLite'],
  },
  {
    title: 'Blockchain Voting System',
    description: 'Secure voting system using blockchain technology',
    goal: Goal.OpenSource,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-12-15'),
    domainLabels: ['Technology', 'Web Development'],
    technicalLabels: ['Python', 'Docker', 'PostgreSQL'],
  },
  {
    title: 'Music Collaboration Platform',
    description: 'Platform for musicians to collaborate remotely',
    goal: Goal.Fun,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-09-30'),
    domainLabels: ['Music', 'Social Media'],
    technicalLabels: ['WebSocket', 'Express', 'MongoDB'],
  },
  {
    title: 'AI Code Review Assistant',
    description: 'AI-powered code review tool',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-11-15'),
    domainLabels: ['Artificial Intelligence', 'Web Development'],
    technicalLabels: ['Python', 'Docker', 'PostgreSQL'],
  },
  {
    title: 'Local Community Board',
    description: 'Digital notice board for local communities',
    goal: Goal.Fun,
    status: ProjectStatus.Complete,
    languageCode: LanguageCode.FR,
    milestone: new Date('2024-06-01'),
    domainLabels: ['Social Media', 'Public Health'],
    technicalLabels: ['PHP', 'MySQL', 'Vue.js'],
  },
  {
    title: 'Educational Game Platform',
    description: 'Platform for creating and playing educational games',
    goal: Goal.Education,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-08-30'),
    domainLabels: ['Education', 'Game Development'],
    technicalLabels: ['Unity', 'C#', 'MongoDB'],
  },
  {
    title: 'Sustainable Fashion Marketplace',
    description: 'Marketplace for sustainable and ethical fashion',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-10-30'),
    domainLabels: ['Fashion', 'E-commerce'],
    technicalLabels: ['Next.js', 'PostgreSQL', 'Redis'],
  },
  {
    title: 'Open Source CAD Software',
    description: 'Free and open source CAD software',
    goal: Goal.OpenSource,
    status: ProjectStatus.OnHold,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-12-31'),
    domainLabels: ['Engineering', 'Design'],
    technicalLabels: ['C++'],
  },
  {
    title: 'Pet Care App',
    description: 'All-in-one app for pet owners',
    goal: Goal.Fun,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-07-15'),
    domainLabels: ['Healthcare', 'Veterinary'],
    technicalLabels: ['React', 'iOS', 'MongoDB'],
  },
  {
    title: 'Digital Art Marketplace',
    description: 'Platform for buying and selling digital art',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-09-15'),
    domainLabels: ['Art', 'E-commerce'],
    technicalLabels: ['React', 'Express', 'MongoDB'],
  },
  {
    title: 'Remote Work Hub',
    description: 'Platform for remote workers to find workspaces',
    goal: Goal.Profitable,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-08-01'),
    domainLabels: ['Social Media', 'Project Management'],
    technicalLabels: ['Django', 'PostgreSQL', 'React'],
  },
  {
    title: 'Open Source Game Engine',
    description: '2D game engine for indie developers',
    goal: Goal.OpenSource,
    status: ProjectStatus.InProgress,
    languageCode: LanguageCode.EN,
    milestone: new Date('2024-11-30'),
    domainLabels: ['Game Development', 'Technology'],
    technicalLabels: ['C++', 'Unity'],
  },
];
