import { UserRole } from '@think-storm/contracts';

export const roles = [
  { name: UserRole.Developer },
  { name: UserRole.SeniorDeveloper },
  { name: UserRole.LeadDeveloper },
  { name: UserRole.FullStackDeveloper },
  { name: UserRole.FrontendDeveloper },
  { name: UserRole.BackendDeveloper },
  { name: UserRole.MobileDeveloper },
  { name: UserRole.Designer },
  { name: UserRole.UIDesigner },
  { name: UserRole.UXDesigner },
  { name: UserRole.GraphicDesigner },
  { name: UserRole.Manager },
  { name: UserRole.ProjectManager },
  { name: UserRole.TechnicalManager },
  { name: UserRole.ProductOwner },
  { name: UserRole.ScrumMaster },
  { name: UserRole.AgileCoach },
  { name: UserRole.Tester },
  { name: UserRole.QAEngineer },
  { name: UserRole.AutomationTester },
  { name: UserRole.SecurityTester },
  { name: UserRole.DevOps },
  { name: UserRole.SRE },
  { name: UserRole.CloudEngineer },
  { name: UserRole.DataScientist },
  { name: UserRole.DataEngineer },
  { name: UserRole.DataAnalyst },
  { name: UserRole.MLEngineer },
  { name: UserRole.BusinessAnalyst },
  { name: UserRole.SystemAnalyst },
  { name: UserRole.SolutionArchitect },
  { name: UserRole.TechnicalArchitect },
  { name: UserRole.SecurityEngineer },
  { name: UserRole.DatabaseAdministrator },
  { name: UserRole.NetworkEngineer },
  { name: UserRole.TechnicalWriter },
  { name: UserRole.ProductManager },
  { name: UserRole.Marketing },
  { name: UserRole.Sales },
  { name: UserRole.CustomerSupport },
  { name: UserRole.Other },
];
