import { Role } from '@prisma/client';

export const roles = [
  { name: 'Developer' },
  { name: 'Senior Developer' },
  { name: 'Lead Developer' },
  { name: 'Full Stack Developer' },
  { name: 'Frontend Developer' },
  { name: 'Backend Developer' },
  { name: 'Mobile Developer' },
  { name: 'Designer' },
  { name: 'UI Designer' },
  { name: 'UX Designer' },
  { name: 'Graphic Designer' },
  { name: 'Manager' },
  { name: 'Project Manager' },
  { name: 'Technical Manager' },
  { name: 'Product Owner' },
  { name: 'Scrum Master' },
  { name: 'Agile Coach' },
  { name: 'Tester' },
  { name: 'QA Engineer' },
  { name: 'Automation Tester' },
  { name: 'Security Tester' },
  { name: 'DevOps' },
  { name: 'SRE' },
  { name: 'Cloud Engineer' },
  { name: 'Data Scientist' },
  { name: 'Data Engineer' },
  { name: 'Data Analyst' },
  { name: 'ML Engineer' },
  { name: 'Business Analyst' },
  { name: 'System Analyst' },
  { name: 'Solution Architect' },
  { name: 'Technical Architect' },
  { name: 'Security Engineer' },
  { name: 'Database Administrator' },
  { name: 'Network Engineer' },
  { name: 'Technical Writer' },
  { name: 'Product Manager' },
  { name: 'Marketing' },
  { name: 'Sales' },
  { name: 'Customer Support' },
  { name: 'Other' }
];
