export const technicalLabel = [
  { name: 'Python' },
  { name: 'JavaScript' },
  { name: 'TypeScript' },
  { name: 'Java' },
  { name: 'C#' },
  { name: 'C++' },
  { name: 'C' },
  { name: 'PHP' },
  { name: 'Ruby' },
  { name: 'Go' },
  { name: 'Swift' },
  { name: 'Kotlin' },
  { name: 'Rust' },
  { name: 'Scala' },
  { name: 'Git' },
  { name: 'Docker' },
  { name: 'Kubernetes' },
  { name: 'Jenkins' },
  { name: 'AWS' },
  { name: 'Azure' },
  { name: 'Google Cloud' },
  { name: 'Heroku' },
  { name: 'Netlify' },
  { name: 'Vercel' },
  { name: 'Firebase' },
  { name: 'MongoDB' },
  { name: 'PostgreSQL' },
  { name: 'MySQL' },
  { name: 'SQLite' },
  { name: 'Redis' },
  { name: 'Elasticsearch' },
  { name: 'Kafka' },
  { name: 'RabbitMQ' },
  { name: 'GraphQL' },
  { name: 'REST API' },
  { name: 'WebSocket' },
  { name: 'Django' },
  { name: 'Flask' },
  { name: 'Express' },
  { name: 'NestJS' },
  { name: 'Spring Boot' },
  { name: 'ASP.NET' },
  { name: 'Ruby on Rails' },
  { name: 'React' },
  { name: 'Angular' },
  { name: 'Vue.js' },
  { name: 'Svelte' },
  { name: 'Next.js' },
  { name: 'Nuxt.js' },
  { name: 'Gatsby' },
  { name: 'Redux' },
  { name: 'MobX' },
  { name: 'Vuex' },
  { name: 'Jest' },
  { name: 'Mocha' },
  { name: 'Chai' },
  { name: 'Cypress' },
  { name: 'Selenium' },
  { name: 'Puppeteer' },
  { name: 'Jasmine' },
  { name: 'Karma' },
  { name: 'Playwright' },
  { name: 'React Testing Library' },
  { name: 'Enzyme' },
  { name: 'Cucumber' },
  { name: 'Jira' },
  { name: 'Trello' },
  { name: 'Unix' },
  { name: 'Linux' },
  { name: 'Windows' },
  { name: 'macOS' },
  { name: 'iOS' },
  { name: 'Android' },
  { name: 'Raspberry Pi' },
  { name: 'Arduino' },
  { name: 'ESP32' },
  { name: 'ESP8266' },
  { name: 'STM32' },
  { name: 'PIC' },
  { name: 'RISC-V' },
  { name: 'ARM' },
  { name: 'x86' },
  { name: 'MIPS' },
  { name: 'PowerPC' },
  { name: 'WebAssembly' },
  { name: 'Assembly' },
  { name: 'Bash' },
  { name: 'PowerShell' },
  { name: 'Zsh' },
  { name: 'Fish' },
  { name: 'Vim' },
  { name: 'Emacs' },
  { name: 'Sublime Text' },
  { name: 'VS Code' },
  { name: 'IntelliJ IDEA' },
  { name: 'Eclipse' },
  { name: 'NetBeans' },
  { name: 'Xcode' },
  { name: 'Android Studio' },
  { name: 'Unity' },
  { name: 'Unreal Engine' },
  { name: 'Godot' },
  { name: 'Blender' },
  { name: 'Docker Compose' },
  { name: 'Kubernetes Helm' },
  { name: 'Terraform' },
];
