name: Global Verification on Schedule

permissions:
  contents: read # for actions/checkout
  packages: read # ← allow pulls from GitHub Packages
  id-token: write # Required for requesting the JWT
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  global-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          contract-access-token: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        uses: ./.github/actions/lint

      - name: Build
        uses: ./.github/actions/build
        with:
          build-args: '--build-arg CONTRACT_ACCESS_TOKEN=${{ secrets.NPM_TOKEN }}'

      - name: Tests
        id: run-tests
        uses: ./.github/actions/run-tests
        with:
          build-args: '--build-arg CONTRACT_ACCESS_TOKEN=${{ secrets.NPM_TOKEN }}'
          env-variables: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            JWT_COOKIE_EXPIRES_IN=${{ secrets.JWT_COOKIE_EXPIRES_IN }}
            ENVELOOP_API_KEY=${{ secrets.ENVELOOP_API_KEY }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            REDIS_CACHING_TTL=${{ secrets.REDIS_CACHING_TTL }}
            REDIS_THROTTLER_URL=${{ secrets.REDIS_THROTTLER_URL }}
            REDIS_CACHING_URL=${{ secrets.REDIS_CACHING_URL }}

      - name: Check Test Results
        if: steps.run-tests.outputs.test-success != 'true'
        run: |
          echo "Tests failed"
          echo "Failed tests: ${{ steps.run-tests.outputs.failed_tests }}"
          exit 1

  dependencies-check:
    needs: global-verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Audit
        run: |
          npm audit
          if [ $? -ne 0 ]; then
            echo "Running npm audit fix..."
            npm audit fix
            if [ -n "$(git status --porcelain)" ]; then
              git config --global user.name 'GitHub Actions Bot'
              git config --global user.email 'actions@github.com'
              git checkout develop
              git add package.json package-lock.json
              git commit -m "fix: npm audit automatic fixes"
              git push origin develop
              echo "Changes from npm audit fix have been committed to develop branch"
            else
              echo "No fixes were applied by npm audit fix"
            fi
            exit 1
          fi
