name: Integration and Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      db-name: build_db
      run-lint: true

  verify-start-prod:
    uses: ./.github/workflows/deploy-databases-and-run.yml
    needs: build
    with:
      test-command: |
        npm run start:prod & 
        echo "Waiting for application to start..."
        sleep 15
        if ! curl -f http://localhost:3000/api/health; then
          echo "Production server failed to start or health check failed"
          exit 1
        fi
        echo "Production server started successfully and health check passed"
      db-name: test_db_verify
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}

  unit-test:
    uses: ./.github/workflows/deploy-databases-and-run.yml
    needs: verify-start-prod
    with:
      test-command: npm run test:unit
      db-name: unit_test_db
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}

  e2e-test:
    uses: ./.github/workflows/deploy-databases-and-run.yml
    needs: verify-start-prod
    with:
      test-command: npm run test:e2e
      db-name: e2e_test_db
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}

  coverage-test:
    uses: ./.github/workflows/deploy-databases-and-run.yml
    needs: verify-start-prod
    with:
      test-command: npm run test:cov
      db-name: coverage_test_db
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, e2e-test, coverage-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy
