# .github/workflows/deploy.yml

name: Deploy to Fly.io

on:
  push:
    branches:
      - test  # Change this to the branch you want to trigger deployment

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify VERSION file
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: VERSION
      - name: Get the version
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          if [[ ! "$VERSION" =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$ ]]; then
            echo "VERSION format is invalid: $VERSION"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create a new tag
        id: tag
        run: |
          TAG_NAME="v${{ env.VERSION }}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          body: |
            Deployed version ${{ env.VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy

